#!/usr/bin/env sh

echo "sh -c \"$@\""
DUMP="$$.out"
sh -c "$@" | tee "/tmp/$DUMP"
RC=$?
LC=`wc -l "/tmp/$DUMP" | awk '/.*/ { print $1 }'`
SOUT="StdIO: $LC Lines (/tmp/$DUMP)"
growlnotify -n mk -appIcon Terminal "Job Complete" \
-m "Job: '$1' 
Exit Status: $RC
$SOUT"

afplay /System/Library/Sounds/Submarine.aiff > /dev/null 2>&1 &
