#!/bin/sh

LC_CTYPE=en_US.UTF-8
SVN=`which svn`

echo Changing to Bundles directory...
mkdir -p "/Library/Application Support/TextMate/Bundles"
cd "/Library/Application Support/TextMate/Bundles"

for i in `cat $HOME/.bash/bundles/bundles.list | awk -F"\n" '{ print $0 }'`
do 
	if [ -d "/Library/Application Support/TextMate/Bundles/$i.tmbundle" ]; then
		echo "$i bundle already exists - updating..."
		$SVN up "$i.tmbundle"
	else
		echo "Checking out $i bundle..."
		$SVN --username anon --password anon co "http://svn.textmate.org/trunk/Bundles/$i.tmbundle/"
	fi
done

$SVN --username anon --password anon co "http://svn.textmate.org/trunk/Review/Bundles/Treetop.tmbundle/"
git clone https://github.com/zuckschwerdt/asciidoc.tmbundle.git "AsciiDoc.tmbundle"
git clone https://github.com/textmate/python-django.tmbundle.git
git clone https://github.com/textmate/python-django-templates.tmbundle.git

echo Reloading bundles in TextMate...
osascript -e 'tell app "TextMate" to reload bundles'

