#!/usr/bin/env sh

LC_CTYPE=en_US.UTF-8

mkdir -p "$HOME/Library/Application Support/vim/plugins"
cd "$HOME/Library/Application Support/vim/plugins"

for i in `cat $HOME/.bash/bundles/plugins.list`
do 
    git clone $i
done

for p in `ls -l $HOME/Library/Application Support/vim/plugins | awk '/./ { print $NF }'`
do
    cp "$p/doc/*" "$HOME/.vim/doc/"
    cp "$p/plugin/*" "$HOME/vim/plugin/"
done

echo 'done'
